theme="noctis_bordo"

[editor]
completion-trigger-len=1
cursorline=true
line-number="relative"
idle-timeout=100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render=true

[editor.lsp]
display-inlay-hints = false
goto-reference-include-declaration = false

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "register", "position", "file-encoding"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = "goto_word"
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"

[keys.select]
ret = "goto_word"

[keys.normal."space"]
x = { v = "vsplit", h = "hsplit"}
C-c = { c = "command_palette", o = ":config-open", r = ":config-reload"}

