# theme="boo_berry_kuba"
# theme="noctis_bordo"
theme="monokai_pro_ristretto"

[editor]
bufferline="multiple" # show top buffer bar when more than one buffer is open
completion-trigger-len=1
completion-timeout=100
cursorline=true
line-number="relative"
idle-timeout=100
end-of-line-diagnostics = "hint" # show end-of-line diagnostic for HINT level and above
scrolloff = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning" # show detailed diagnostics for WARNING level and above when on that line

[editor.lsp]
display-inlay-hints = true
goto-reference-include-declaration = false

[editor.smart-tab]
enable = false

[editor.soft-wrap]
enable = false

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "register", "position", "file-encoding"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = "goto_word"

A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"

A-w = "move_next_sub_word_start"
A-b = "move_prev_sub_word_start"
A-e = "move_next_sub_word_end"
A-E = "move_prev_sub_word_end"

S-h = "goto_previous_buffer"
S-l = "goto_next_buffer"

C-x = ":reset-diff-change"
C-r = "redo"

"*" = ["search_selection", "make_search_word_bounded", "search_next"]

backspace = { a = "goto_next_parameter", d = "goto_next_diag", f = "goto_next_function",  A = "goto_prev_parameter", D = "goto_prev_diag", F = "goto_prev_function" }

[keys.select]
ret = "goto_word"

[keys.normal."space"]
x = { v = "vsplit", h = "hsplit"}
C-c = { c = "command_palette", o = ":config-open", r = ":config-reload"}
q = ":buffer-close"
