[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff"]

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true

[[language]]
name = "go"
language-servers = [ { name = "gopls", except-features = [ "inlay-hints" ] } ]

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }
